[package]
edition = "2021"
name = "projects_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "projects_integrity"

[dependencies]
hdi = "0.2.0"
holo_hash = { version = "0.1.0", features = ["encoding"] }
serde = "*"
thiserror = "1"
