[workspace]
members = [
  # "happ/tests/projects",
  # "happ/tests/profiles",
  "happ/zomes/profiles",
  "happ/zomes/profiles_integrity",
  "happ/zomes/projects",
  "happ/zomes/projects_integrity",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"